# Generate powerpoint slide of matrix

Generate powerpoint slide containing current version of framework

Cool thing to do, but there are other things to do first (like, for now, an html table will do).

In [14]:
# Load in AMITT details
import pandas as pd
arr = pd.read_csv('../matrices/matrix_arr.csv', header=None)
arr

,0,1,2,3,4,5,6,7,8,9,10,11
0,P01,P01,P02,P02,P02,P02,P02,P03,P03,P03,P03,P04
1,TA01,TA02,TA03,TA04,TA05,TA06,TA07,TA08,TA09,TA10,TA11,TA12
2,T0001,T0005,T0007,T0010,T0016,T0019,T0029,T0039,T0047,T0057,T0058,NaN
3,T0002,T0006,T0008,T0011,T0017,T0020,T0030,T0040,T0048,NaN,T0059,NaN
4,T0003,NaN,T0009,T0012,T0018,T0021,T0031,T0041,T0049,NaN,T0060,NaN
5,T0004,NaN,NaN,T0013,NaN,T0022,T0032,T0042,T0050,NaN,NaN,NaN
6,NaN,NaN,NaN,T0014,NaN,T0023,T0033,T0043,T0051,NaN,NaN,NaN
7,NaN,NaN,NaN,T0015,NaN,T0024,T0034,T0044,T0052,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,T0025,T0035,T0045,T0053,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,T0026,T0036,T0046,T0054,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,T0027,T0037,NaN,T0055,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,T0028,T0038,NaN,T0056,NaN,NaN,NaN

In [20]:
from pptx import Presentation
from pptx.util import Inches

prs = Presentation()
slide = prs.slides.add_slide(prs.slide_layouts[6]) # blank slide
shapes = slide.shapes

# shapes.title.text = 'AMITT'

cols = len(arr.columns)
rows = len(arr)
left = top = Inches(0.5)
width = Inches(9)
height = Inches(0.5)

table = shapes.add_table(rows, cols, left, top, width, height).table

# set column widths
# table.columns[0].width = Inches(2.0)
# table.columns[1].width = Inches(4.0)

# write column headings
table.cell(0, 0).text = 'Foo'
table.cell(0, 1).text = 'Bar'

# write body cells
table.cell(1, 0).text = 'Baz'
table.cell(1, 1).text = 'Qux'

prs.save('test.pptx')